apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: graphql-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graphql-deployment
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
