apiVersion: apps/v1
kind: Deployment
metadata:
 name: graphql-deployment
spec: 
 selector: 
  matchLabels: 
   app: graphql-label
 replicas: 2
 template: 
  spec: 
   containers: 
     - name: node-graphql
       image: graphql_api:1.0.0
       imagePullPolicy: Never
       ports: 
        - containerPort: 4000
  metadata:
   labels:
    app: graphql-label